export const DEFAULT_SPECIES = [
  { deName: "Ahorn", botanicalName: "Acer platanoides" },
  { deName: "Birke", botanicalName: "Betula pendula" },
  { deName: "Buche", botanicalName: "Fagus sylvatica" },
  { deName: "Eberesche", botanicalName: "Sorbus aucuparia" },
  { deName: "Eiche", botanicalName: "Quercus robur" },
  { deName: "Erle", botanicalName: "Alnus glutinosa" },
  { deName: "Esche", botanicalName: "Fraxinus excelsior" },
  { deName: "Hainbuche", botanicalName: "Carpinus betulus" },
  { deName: "Kastanie", botanicalName: "Aesculus hippocastanum" },
  { deName: "Kiefer", botanicalName: "Pinus sylvestris" },
  { deName: "Kirsche", botanicalName: "Prunus avium" },
  { deName: "Lärche", botanicalName: "Larix decidua" },
  { deName: "Linde", botanicalName: "Tilia cordata" },
  { deName: "Magnolie", botanicalName: "Magnolia kobus" },
  { deName: "Pappel", botanicalName: "Populus nigra" },
  { deName: "Platane", botanicalName: "Platanus x hispanica" },
  { deName: "Robinie", botanicalName: "Robinia pseudoacacia" },
  { deName: "Tanne", botanicalName: "Abies alba" },
  { deName: "Ulme", botanicalName: "Ulmus minor" },
  { deName: "Weide", botanicalName: "Salix alba" },
] as const;
